### PR TITLE
chore: update plugin

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
This PR contains a:

- [x] **bugfix**
- [x] new **feature**
- [x] **code refactor**
- [x] **test update** 
- [x] **typo fix**
- [x] **metadata update**

#### ✨ &nbsp; New Options

- Exclude (Specify the files and/or directories to exclude. Must be relative to `options.context`)
- Extensions (Specify extensions that should be checked)
- Output Report (Write the output of the errors to a file, for example a `json` file for use for reporting)
- Threads

#### Refactor

* Updates to emitError and emitWarning

Setting only emitError to true will no longer exclusively print files with errors
and disregard the files with warnings. Similarly, setting only emitWarning to true
will no longer exclusively print files with warnings disregard the files with errors.

* fix: use quiet to override emitError and emitWarning

- quiet is essentially syntactic sugar for setting emitError to true
and emitWarning to false

### Additional Info

This plugin has been rewritten to work only with import graph files, reducing its execution time and linting necessary files.
It will probably be the last release with support for webpack 4.

### CODE REVIEW

**Comment by ricardogobbosouza** [comment]
Hi @jsg2021
Your review would be very helpful, since this plugin is very similar to `eslint-webpack-plugin`

**Review by jsg2021 — COMMENTED** [review]
At a high level, it looks good to me. Any idea why it doesn't work with threads?

**Comment by ricardogobbosouza** [comment]
> At a high level, it looks good to me. Any idea why it doesn't work with threads?

@jsg2021 
Some problem with the [`stylelint.lint` function](https://github.com/webpack-contrib/stylelint-webpack-plugin/pull/230/files?file-filters%5B%5D=.js&file-filters%5B%5D=.json&file-filters%5B%5D=.scss&file-filters%5B%5D=.ts#diff-a19812fe5175f5ae8fccdf2c9400b66ea4408f519c4208fded5ae4c3365cac4dR32). 
Error: `DataCloneError: [object Function] could not be cloned.`

**Comment by ricardogobbosouza** [comment]
I managed to solve it by writing the result, strange, but it worked ...

```js
// Reset result to work with worker
  return results.map((result) => {
    return {
      source: result.source,
      errored: result.errored,
      ignored: result.ignored,
      warnings: result.warnings,
      deprecations: result.deprecations,
      invalidOptionWarnings: result.invalidOptionWarnings,
    };
  });
```

**Comment by ricardogobbosouza** [comment]
@alexander-akait unfortunately not, I commented here https://github.com/webpack-contrib/stylelint-webpack-plugin/blob/feat-update-plugin/src/index.js#L183

**Comment by alexander-akait** [comment]
@ricardogobbosouza It is only for initial lint?

**Comment by ricardogobbosouza** [comment]
@alexander-akait it looked like this:
- When the webpack starts, all style sheets will be linted, regardless of whether they are being used or not.
- After initialization, only the files modified will be linted

**Comment by ricardogobbosouza** [comment]
The idea was to get the dependencies of the stylesheet module, to really linting only the files used, but the only way I found was using `module.buildInfo.snapshot` which is not recommended, maybe leave this improvement for v3 where we will depreciate the support for webpack4.

**Comment by alexander-akait** [comment]
@ricardogobbosouza sorry for delay, I agree, let's postpone, also we can improve it in any time in future

**Comment by alexander-akait** [comment]
@ricardogobbosouza friendly ping

**Comment by ricardogobbosouza** [comment]
@alexander-akait I'm waiting for your review 😄

**Review by alexander-akait — APPROVED** [review]

**Pull request merged**
