### PR TITLE
Add webpack4 support;

### PR DESCRIPTION
**Pull request by KyKyPy3**
Providing ability to run on webpack 4

### CODE REVIEW

**Comment by KyKyPy3** [comment]
#137

**Comment by mtraynham** [comment]
@KyKyPy3 this does seem like the appropriate solution to upgrading to Webpack 4, but you've changed the `package.json` name and urls.  Not sure if you meant to do that within this PR.  Either way, this will still complain about Webpack versioning.

Might I suggest moving your last commit into a personal branch and adding a new commit here for the peerDependency version fix.

**Comment by KyKyPy3** [comment]
Fix it

**Comment by stevenleija** [comment]
Is there an ETA on when this gets merged and published?

**Comment by mgoodings** [comment]
Whilst waiting for this to be updated and until the rewrite from @JaKXz is available I've created a simplistic plugin that supports Webpack 4.

https://github.com/mgoodings/easy-stylelint-plugin

**Comment by shellscape** [comment]
@KyKyPy3 this project has just moved into the `webpack-contrib` org. We'd very much like to merge your PR but we'll need you to sign the CLA first (see above).

**Comment by shellscape** [comment]
As we could not get ahold of the author of this PR, we have created #144.

**Pull request closed without merging**
