### PR TITLE
feat: support .stylelintignore file

### PR DESCRIPTION
**Pull request by BlackHole1**
This PR contains a:

- [ ] **bugfix**
- [x] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

https://github.com/webpack-contrib/stylelint-webpack-plugin/issues/105

### CODE REVIEW

**Review by ricardogobbosouza — APPROVED** [review]

**Review by alexander-akait — COMMENTED** [review]
In my option, stylelint should have API to do it, otherwise they can change logic and it will be problem for us, we need ping somebody from stylelint here

@ybiquitous @jeddy3 

Any advices? I haven't worked directly with api for a long time, so maybe I'm missing something, thanks

**Comment by ricardogobbosouza** [comment]
@alexander-akait  You're right
I just did a test and stylelint handles it perfectly.

**Comment by ricardogobbosouza** [comment]
Hi @BlackHole1 
Better let `stylelint` handle it itself

**Comment by BlackHole1** [comment]
hi @ricardogobbosouza , I have an example to describe why this should be done.

Please reopen this pr and I'll submit a `gist/repo` later to explain why I'm doing this.

**Comment by ricardogobbosouza** [comment]
@BlackHole1 Please share a repository where this issue occurs. So I can reanalyze the PR

**Comment by BlackHole1** [comment]
okey

**Comment by BlackHole1** [comment]
repo: https://github.com/BlackHole1/stylelint-webpack-plugin-PR-257/tree/main

cc: @ricardogobbosouza

**Comment by BlackHole1** [comment]
On its own, it is fine to decouple the logic of the plugin from `stylelint` itself. But based on the user's experience, it is better for the user that we have proper coupling.

**Comment by BlackHole1** [comment]
For example, I'll use vscode-stylelint as an example: https://github.com/stylelint/vscode-stylelint/blob/59be6cc89d04ed5efaf122c838ac31003d15de4f/src/extension/extension.ts#L38

This plugin recognises `.stylelintignore`, not `stylelint-webpack-plugin -> exclude`

**Comment by alexander-akait** [comment]
Ideally stylelint should iself ignore them (i.e. loader .stylelintignore and do not report warnings/errors for these patterns), maybe we forget something to setup?

**Comment by BlackHole1** [comment]
In eslint, a warning will be reported instead of an error

图片

**Comment by BlackHole1** [comment]
In stylelint, this error is expected. see:
https://github.com/stylelint/stylelint/blob/060310cfd6383175ee06fe4d15aee27a4e202671/lib/standalone.js#L261

**Comment by BlackHole1** [comment]
Perhaps I should submit a PR to stylelint to add an option to control whether `not found file` errors are reported?

**Comment by alexander-akait** [comment]
I think it s good way, let's open an issue and discuss it, I'm not against it, I just would like to avoid duplicate code and found valid way to solve it

**Comment by ricardogobbosouza** [comment]
@BlackHole1
In my opinion we should return the same as `stylelint`, after all this is a plugin for it.

In your https://github.com/BlackHole1/stylelint-webpack-plugin-PR-257 repo, if we run `stylelint src/**.css` it returns the same error as `npx webpack ./src/index.js --mode=development`

We shouldn't treat it differently.

And if we don't have stylesheets to lint, it doesn't make sense to have the plugin configured, don't you think?

**Comment by BlackHole1** [comment]
> @BlackHole1 In my opinion we should return the same as `stylelint`, after all this is a plugin for it.
> 
> In your https://github.com/BlackHole1/stylelint-webpack-plugin-PR-257 repo, if we run `stylelint src/**.css` it returns the same error as `npx webpack ./src/index.js --mode=development`
> 
> We shouldn't treat it differently.
> 
> And if we don't have stylesheets to lint, it doesn't make sense to have the plugin configured, don't you think?

I agree:
> stylelint src/**.css it returns the same error as npx webpack ./src/index.js --mode=development

But this is because I only have one css file, if I had two css files then the situation would be different

**Comment by BlackHole1** [comment]
Oooh, Sorry. Their behaviour is consistent

**Comment by BlackHole1** [comment]
I'm sorry I didn't add some details. I've only just recalled the full details because it's been a bit too long. Please wait a moment while I refine the entire description of the problem.

**Comment by ricardogobbosouza** [comment]
If I have 2 or more files and they are all ignored then I don't have any.

But if I have at least 1 valid file, it will go through lint normally.

**Comment by BlackHole1** [comment]
The problem is with `watch`. 
I've just pushed the code, you can revisit it https://github.com/BlackHole1/stylelint-webpack-plugin-PR-257

When a user starts watch and modifies an ignored css file, they will get an error

图片

**Comment by ricardogobbosouza** [comment]
Ok. When watching we have this problem

**Comment by BlackHole1** [comment]
I've come up with an idea to get around this error by passing in the allowEmptyInput parameter when the current mode is watch.

**Comment by ricardogobbosouza** [comment]
> Eu tive uma ideia para contornar esse erro passando

But I think it's not the most correct

**Comment by BlackHole1** [comment]
> > Eu tive uma ideia para contornar esse erro passando
> 
> But I think it's not the most ideal

Oh? Can you describe your reasoning?🧐

Because it seems to me that this is a way to be consistent with `stylelint` without having to deal with `.stylelintignore`

**Comment by ybiquitous** [comment]
Hi there, I'm a maintainer of Stylelint. ✋🏼 

Maybe, [`stylelint/lib/utils/getFileIgnorer.js`](https://github.com/stylelint/stylelint/blob/9e75552d5da4f4448208a65b0c6f876ef9a0feb0/lib/utils/getFileIgnorer.js) may be useful in such a case, though the module is internal and its return type is one of the [`ignorer`](https://github.com/erickzanardo/ignorer) package.

Of course, you can also open an issue to suggest a new API for the case. Here are the discussion issues about new APIs:
https://github.com/stylelint/stylelint/issues?q=is%3Aissue+is%3Aopen+Expose+

**Comment by ricardogobbosouza** [comment]
@BlackHole1 
https://github.com/webpack-contrib/stylelint-webpack-plugin/pull/257#issuecomment-1014743474

My thought is, that if the file is skipped, it shouldn't go through lint even in watch mode.
The `stylelint` is running unnecessarily in this case

**Comment by BlackHole1** [comment]
Perhaps we should export `stylelint/lib/utils/getFileIgnorer.js` function, and use?

**Comment by ricardogobbosouza** [comment]
The `stylelint` could have in its api a function `stylelint.isFileIgnored(path)`

**Comment by BlackHole1** [comment]
> The `stylelint` could have in its api a function `stylelint.isFileIgnored(path)`

Good idea. I'll submit a PR to `stylelint` later

**Pull request closed without merging**
