### PR TITLE
chore(release): 0.10.6

### PR DESCRIPTION
**Pull request by avrelaun**

### CODE REVIEW

**Comment by avrelaun** [comment]
Fails on node6-latest but no big changes from 0.10.5... stylelint 9 should still supports node 6

**Comment by avrelaun** [comment]
All tests run locally on node 6.14.3

**Comment by avrelaun** [comment]
I cannot seem to figure out what's the problem with the build, could someone help ?

**Comment by patrickabkarian** [comment]
it's supposed to fail

**Comment by patrickabkarian** [comment]
https://github.com/webpack-contrib/stylelint-webpack-plugin/pull/165

If this gets merged than this pull request can be merged too.

**Comment by evilebottnawi** [comment]
@avrelaun tests failed, we should fix it

**Comment by brneto** [comment]
Take a look to this: [Update docs for NoErrorsPlugin deprecation and rename to NoEmitOnErrorsPlugin](https://github.com/webpack/docs/issues/96)
and
this: [optimization.noEmitOnErrors](https://webpack.js.org/configuration/optimization/#optimization-noemitonerrors)

I think the errors has something to do with the above links.

**Comment by ntwb** [comment]
It looks the single test failure in this PR would be fixed by merging #163

**Pull request closed without merging**
