### PR TITLE
v1.0.0

### LINKED ISSUE #138: Wrong documentation for `emitErrors`
The documentation says `emitErrors` defaults to `true`, but it makes a difference if you set it to `true` instead of omitting the option.

I use the NoEmitOnErrorsPlugin. When I set `emitErrors: true` it works correctly, when I don't (leave it undefined), it shows the errors but generates my `dist` folder.

Maybe not related, but what I tried before was setting `failOnError: true`. This successfully breaks my build but shows me the following instead of an useful error message:

> node:50144) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'toString' of undefined
> (node:50144) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### LINKED ISSUE #151: How to get the detailed error info when ‘failOnError’ setted to true？
When the stylelint error happen, I want stop the webpack process and get the detailed error info. But if
I set failOnError to true. The log is not clear：

Error: Failed because of a stylelint error.

    at linterSuccess (/Users/lidasong/Documents/projects/appstore-rn/h5/node_modules/stylelint-webpack-plugin/lib/run-compilation.js:39:14)

### LINKED ISSUE #170: DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
* Operating System: Debian 9
* Node Version: 10.14.2
* NPM Version: 6.4.1
* webpack Version: 4.29.5
* stylelint-webpack-plugin Version: 0.10.5

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [x] **modification** request

##### CLI Command

```bash
  $ node --trace-deprecation ./node_modules/.bin/webpack-dev-server --open --config webpack.dev.js
```

### Expected Behavior

No deprecation warnings are thrown

### Actual Behavior

```
(node:12431) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at new LintDirtyModulesPlugin (/home/<snip>/node_modules/stylelint-webpack-plugin/lib/lint-dirty-modules-plugin.js:20:12)
    at stylelintWebpackPlugin.apply (/home/<snip>/node_modules/stylelint-webpack-plugin/index.js:31:5)
    at webpack (/home/<snip>/node_modules/webpack/lib/webpack.js:47:13)
    at startDevServer (/home/<snip>/node_modules/webpack-dev-server/bin/webpack-dev-server.js:335:16)
    at processOptions (/home/<snip>/node_modules/webpack-dev-server/bin/webpack-dev-server.js:309:5)
    at Object.<anonymous> (/home/<snip>/node_modules/webpack-dev-server/bin/webpack-dev-server.js:424:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```
it still works after this though, but relying on deprecated APIs doesn't seem like a good idea.

### LINKED ISSUE #171: Release version with latest changes
This issue is for a:

- [ ] **bug**
- [ ] **feature** request
- [x] **modification** request

### Expected Behavior

Latest change (a dependency version bump) is released.

### Actual Behavior

It is not.

### LINKED ISSUE #174: Update peer dependencies to support stylelint 10
Hi there,

Stylelint v10 have been released with a lot of fix.
It could be nice if you update the peer dependencies and release a new npm version to support v10?

For now, I'm actually getting this on the console:

`npm WARN stylelint-webpack-plugin@0.10.5 requires a peer of stylelint@^8.0.0 but none is installed. You must install peer dependencies yourself.`

Cheers 👍

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
This PR contains a:

- [x] **bugfix**
- [x] new **feature**
- [x] **code refactor**
- [x] **test update** 
- [x] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

- [x] New/Update options
    - stylelintPath (new)
    - emitError (update)
    - emitWarning (new)
    - failOnError (update)
    - failOnWarning (new)
    - quiet (new)
- [x] Modernize project to latest defaults
- [x] Validate options
- [x] Increase coverage to 100% 
- [x] Resolve issues
    - Resolve #138
    - Resolve #151 
    - Resolve #177
    - Resolve #174
    - Resolve #171
    - Resolve #170
    - Resolve #163
    - Resolve #157

### Breaking Changes

- Drop support for Node < 8.9.0
- Minimum supported `webpack` version is 4
- Minimum supported `stylelint` version is 9

### CODE REVIEW

**Comment by jimblue** [comment]
@ricardogobbosouza tks for the hard work!
I love this PR :heart:

**Comment by evilebottnawi** [comment]
@ricardogobbosouza ping me when work will be ready :+1: Good job!

**Comment by ricardogobbosouza** [comment]
It's all refactored and with new features, I just need to improve testing by increasing coverage.
As soon as I finish I warn you

**Comment by ricardogobbosouza** [comment]
@evilebottnawi finally, its ready

**Comment by ricardogobbosouza** [comment]
@evilebottnawi Here too I can not merge

**Comment by evilebottnawi** [comment]
@ricardogobbosouza done, need setup azure pipelines here, in my todo on tomorrow

**Comment by ricardogobbosouza** [comment]
@evilebottnawi ok

**Comment by ricardogobbosouza** [comment]
Bug on azure pipelines :disappointed: 
Stopped on MacOS

**Comment by ricardogobbosouza** [comment]
@evilebottnawi I can help keep this plugin too

**Comment by evilebottnawi** [comment]
@ricardogobbosouza i know, some busy right now, will try to find time in near future (today late)

**Comment by evilebottnawi** [comment]
@ricardogobbosouza can you send other PR with only `azure-pipelines.yml` file, i can't setup azure pipelines using your branch

**Comment by ricardogobbosouza** [comment]
@evilebottnawi im sending now

**Comment by evilebottnawi** [comment]
@ricardogobbosouza can you rebase?

**Comment by ricardogobbosouza** [comment]
@evilebottnawi branch master protected
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: 9 of 9 required status checks are expected. At least 1 approving review is required by reviewers with write access.

**Comment by jimblue** [comment]
Hi @ricardogobbosouza and tks for the good work on this PR.
Did you publish it under a different name on NPM?
I can't found the version 1.0.0.

**Comment by ricardogobbosouza** [comment]
@jimblue 
I have no permission on the master branch, I haven't released version 1.0.0 yet

**Comment by evilebottnawi** [comment]
@ricardogobbosouza try again

**Comment by ricardogobbosouza** [comment]
@evilebottnawi works now  =)

**Comment by ricardogobbosouza** [comment]
@evilebottnawi, @jimblue released v1.0.0

**Comment by evilebottnawi** [comment]
Great news

**Pull request merged**
