### PR TITLE
Support css, sass, less by default

### LINKED ISSUE #8: Add support for CSS and LESS files by default
Current default regexp match `SCSS` and `SASS` files only

### PR DESCRIPTION
**Pull request by barraponto**
Fixes #8

### CODE REVIEW

**Comment by barraponto** [comment]
@JaKXz sounds good. Will work on it later this week and submit for review.

**Comment by shellscape** [comment]
@barraponto hey there 🍺  this project has just moved into the `webpack-contrib` org and we'll need you to sign the CLA (see above) before we can take a look at merging this PR.

And given the age of the PR, we were wondering if you're still interested in getting this merged, and/or adding tests for your changes.

**Comment by shellscape** [comment]
@barraponto we'd like to get this merged, but we need you to sign the CLA first. please see above.

**Comment by d3viant0ne** [comment]
@barraponto - This will require a rebase against current master & can / should be reopened.

**Pull request closed without merging**
